[package]
name = "autometrics"
version = "0.1.0"
edition = "2021"

[dependencies]
autometrics-macros = { path = "./macros" }
const_format = { version = "0.2.30", features = ["rust_1_51"] }
opentelemetry = { version = "0.18.0", features = ["metrics"] }

[dev-dependencies]
opentelemetry-prometheus = { version = "*", features = ["prometheus-encoding"] }
strum = { version = "*", features = ["derive"] }
