[package]
name = "autometrics-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
base64 = "0.21.0"
proc-macro2 = "1.0.49"
quote = "1.0.23"
strum_macros = "0.24.3"
syn =  { version = "1.0.107", features = ["extra-traits", "full"] }
url = "2.3.1"
